language: csharp
sudo: required
dotnet: 3.1
mono: none
dist: xenial
install:
  - dotnet restore
before_script:
  - chmod -R a+x scripts
script:
  - dotnet build Isidore.MagicMirror.sln
  - ./scripts/test.sh
  - dotnet publish -c Release
  - cd src/Isidore.MagicMirror.Docker && docker-compose build