language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.4
branches:
  only:
    - master
    - develop
    - build-server
before_script:
  - chmod -R a+x scripts
script:  
  - dotnet restore
  - dotnet build
  - ./scripts/test.sh