language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
branches:
  only:
    - master
    - develop
    - build-server
before_script:
  - chmod -R a+x scripts
os:  
  - linux
install:  
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
script:  
  - dotnet restore
  - dotnet build ./**/project.json
  - ./scripts/test.sh