version: '2'

services:
  isidore.magicmirror.api:
    image: isidore.magicmirror.api
    build:
      context: ./src/Isidore.MagicMirror.API
      dockerfile: Dockerfile
    links:
      - isidore.magicmirror.mongo
  isidore.magicmirror.mongo:
    image: mongo:3.0.4
    #volumes:
    #  - c:\\mongodb:/data/db
    ports:
      - "27017:27017"
      - "28017:28017"
    command: --smallfiles --rest --noauth