version: '3.4'

services:
  isidore.magicmirror.api:
    image: isidore.magicmirror.api
    build:
      context: ../Isidore.MagicMirror.Users/Isidore.MagicMirror.Users.API
      dockerfile: Dockerfile
      args:
        source: "/bin/Release/netcoreapp2.1/publish"
    links:
      - isidore.magicmirror.mongo:mongo-db
  isidore.magicmirror.mongo:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
      - "28017:28017"
    command: --smallfiles --rest --noauth