version: '3.7'

services:
  isidore.magicmirror.users.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7010:80"
    volumes:
      - ${AppData}\microsoft\UserSecrets\:/root/.microsoft/usersecrets/:ro
  isidore.magicmirror.widgets.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7011:80"
    volumes:
      - ${AppData}\microsoft\UserSecrets\:/root/.microsoft/usersecrets/:ro